//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceDA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Account : INotifyPropertyChanged
    {


        string _UserName, _Password, _Image, _ModuleAccount, _PhoneNumber, _CreditCardNumber, _Address, _TaxCode;
        int _LevelAccount;
        public int Id { get; set; }
        public string UserName
        {
            get => _UserName;
            set
            {
                if (_UserName != value)
                {
                    _UserName = value;
                    OnPropertyChanged();
                }
            }
        }
        public string Password
        {
            get => _Password;
            set
            {
                if (_Password != value)
                {
                    _Password = value;
                    OnPropertyChanged();
                }
            }
        }
        public string Image
        {
            get => _Image;
            set
            {
                if (_Image != value)
                {
                    _Image = value;
                    OnPropertyChanged();
                }
            }
        }
        public string ModuleAccount
        {
            get => _ModuleAccount;
            set
            {
                if (_ModuleAccount != value)
                {
                    _ModuleAccount = value;
                    OnPropertyChanged();
                }
            }
        }
        public Nullable<int> LevelAccount
        {
            get => _LevelAccount;
            set
            {
                if (_LevelAccount != value)
                {
                    _LevelAccount = (int)value;
                    OnPropertyChanged();
                }
            }
        }
        public string PhoneNumber
        {
            get => _PhoneNumber;
            set
            {
                if (_PhoneNumber != value)
                {
                    _PhoneNumber = value;
                    OnPropertyChanged();
                }
            }
        }
        public string CreditCardNumber
        {
            get => _CreditCardNumber;
            set
            {
                if (_CreditCardNumber != value)
                {
                    _CreditCardNumber = value;
                    OnPropertyChanged();
                }
            }
        }
        public string Address
        {
            get => _Address;
            set
            {
                if (_Address != value)
                {
                    _Address = value;
                    OnPropertyChanged();
                }
            }
        }
        public string TaxCode
        {
            get => _TaxCode;
            set
            {
                if (_TaxCode != value)
                {
                    _TaxCode = value;
                    OnPropertyChanged();
                }
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        void OnPropertyChanged([CallerMemberName] string propertyName = "")
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
