//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public string Describe { get; set; }
        public int Id { get; set; }
        public string Time { get; set; }
        public string Directors { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<int> TypeMedia { get; set; }
        public string Actor { get; set; }
        public Nullable<double> IMDB { get; set; }
        public string FileFormat { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> Genre { get; set; }
    }
}
