//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile : INotifyPropertyChanged
    {
        public int IdAccount { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
