//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceDA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLMEDIAEntities : DbContext
    {
        public QLMEDIAEntities()
            : base("name=QLMEDIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<KindOfVideo> KindOfVideos { get; set; }
        public virtual DbSet<ListMediaLike> ListMediaLikes { get; set; }
        public virtual DbSet<ListMediaView> ListMediaViews { get; set; }
        public virtual DbSet<Medium> Media { get; set; }
        public virtual DbSet<MyPlayList> MyPlayLists { get; set; }
        public virtual DbSet<PaymentHistory> PaymentHistories { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
    }
}
